kind: Pod
apiVersion: v1
metadata:
  name: resources
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      # soft limit
      requests:
       cpu: "250m"
       memory: "128mi"
      # limits should be atleast or more than requests i.e hard limit
      limits:
       cpu: "250m"
       memory: "128Mi" 
   